################################################################################
### Copyright (C) 2018 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause
################################################################################
---
- hosts: servers_migration
  tasks:
    - name: Set underlay mode
      set_fact:
        underlay_mode: "false"
      when: underlay_mode is not defined
    - name: Generate underlay config file
      template:
        src: ../templates/nsx-baremetal.j2
        dest: /etc/vmware/nsx/nsx-baremetal.xml
        owner: nsx-agent
        group: nsx-agent
        mode: 0660
    - name: load underlay config file
      command: ovs-appctl -t /var/run/vmware/nsx-agent/nsxa-ctl bms/underlay-config
