################################################################################
### Copyright (C) 2018 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
################################################################################
- name: get transport node uuid
  command: bash -c "grep -oP '(?<=UUID>)[^<]+' /etc/vmware/nsx/controller-info.xml"
  register: tn_uuid
- name:
  fail: msg="invalid transport node uuid"
  when: tn_uuid.stdout == ""
