################################################################################
### Copyright (C) 2018 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
################################################################################
---
- hosts: TransportNodes
  tasks:
    - name: is ubuntu
      stat:
        path: /etc/lsb-release
      register: ubuntu_stat_result
    - name: is rhel
      stat:
        path: /etc/redhat-release
      register: rhel_stat_result
    - name: is suse
      stat:
        path: /etc/SuSE-release
      register: suse_stat_result
    - name: get lsb-release
      command: cat /etc/lsb-release
      register: ubuntu_version
      when: ubuntu_stat_result.stat.exists == True
    - name: create check rhel dependency script
      template:
        src: templates/check_rhel_dependency.j2
        dest: /tmp/check_rhel_dependency.sh
        owner: root
        group: root
        mode: 0755
      when: rhel_stat_result.stat.exists == True
    - name: create check suse dependency script
      template:
        src: templates/check_suse_dependency.j2
        dest: /tmp/check_suse_dependency.sh
        owner: root
        group: root
        mode: 0755
      when: suse_stat_result.stat.exists == True
    - name: create check ubuntu16 dependency script
      template:
        src: templates/check_ubuntu16_dependency.j2
        dest: /tmp/check_ubuntu16_dependency.sh
        owner: root
        group: root
        mode: 0755
      when: (ubuntu_stat_result.stat.exists == True) and (ubuntu_version.stdout.find("=16") != -1)
    - name: create check ubuntu18 dependency script
      template:
        src: templates/check_ubuntu18_dependency.j2
        dest: /tmp/check_ubuntu18_dependency.sh
        owner: root
        group: root
        mode: 0755
      when: (ubuntu_stat_result.stat.exists == True) and (ubuntu_version.stdout.find("=18") != -1)
    - name: run check rhel dependency script
      command: bash /tmp/check_rhel_dependency.sh
      when: rhel_stat_result.stat.exists == True
    - name: run check suse dependency script
      command: bash /tmp/check_suse_dependency.sh
      when: suse_stat_result.stat.exists == True
    - name: run check ubuntu16 dependency script
      command: bash /tmp/check_ubuntu16_dependency.sh
      when: (ubuntu_stat_result.stat.exists == True) and (ubuntu_version.stdout.find("=16") != -1)
    - name: run check ubuntu18 dependency script
      command: bash /tmp/check_ubuntu18_dependency.sh
      when: (ubuntu_stat_result.stat.exists == True) and (ubuntu_version.stdout.find("=18") != -1)
    - name: set rhel dependency
      set_fact:
        dependency: "{{ rhel_dependency }}"
      when: rhel_stat_result.stat.exists == True
    - name: set ubuntu16 dependency
      set_fact:
        dependency: "{{ ubuntu16_dependency }}"
      when: (ubuntu_stat_result.stat.exists == True) and (ubuntu_version.stdout.find("=16") != -1)
    - name: set ubuntu18 dependency
      set_fact:
        dependency: "{{ ubuntu18_dependency }}"
      when: (ubuntu_stat_result.stat.exists == True) and (ubuntu_version.stdout.find("=18") != -1)
    - name: set suse dependency
      set_fact:
        dependency: "{{ suse12_dependency }}"
      when: (suse_stat_result.stat.exists == True)
    - name: install rhel or debian dependency
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ dependency }}"
      when: (ubuntu_stat_result.stat.exists == True) or (rhel_stat_result.stat.exists == True)
    - name: install suse dependency
      zypper:
        name: "{{ dependency }}"
        state: present
      when: (suse_stat_result.stat.exists == True)
