# Copyright (c) 2018 VMware, Inc.  All rights reserved
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  tasks:
    - name: get all lsp
      uri:
        url: https://{{ hostvars.nsxmanager.ip }}/api/v1/logical-ports
        method: GET
        user: "{{ hostvars.nsxmanager.username }}"
        password: "{{ hostvars.nsxmanager.password }}"
        headers:
          Content-Type: "application/json"
        return_content: yes
        force_basic_auth: yes
        validate_certs: no
        status_code: 200
        body_format: json
      register: lsp_response
    - name: get lsp list
      set_fact: apply_to="{{ apply_to|default([]) + [ item.id ] }}"
      with_items: "{{ lsp_response.json.results }}"
      when: item.id not in "{{ hostvars.quarantine.lsp }}"
    - name: print apply_to
      debug: var=apply_to
    - name: post rule
      uri:
        url: https://{{ hostvars.nsxmanager.ip }}/api/v1/firewall/sections?action=create_with_rules
        method: POST
        user: "{{ hostvars.nsxmanager.username }}"
        password: "{{ hostvars.nsxmanager.password }}"
        headers:
          Content-Type: "application/json"
        body: "{{ lookup('template', 'quarantine_rule_properties.json.j2') }}"
        return_contents: yes
        force_basic_auth: yes
        validate_certs: no
        status_code: 201
        body_format: json
