################################################################################
### Copyright (C) 2018 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause
################################################################################
---
- hosts: servers_static
  any_errors_fatal: true
  tasks:
    - name: config underlay mode
      set_fact:
        config_mode: 'config_mode=static'
        underlay_mode: 'false'
    - import_tasks: system/get_os_type.yml
    - import_tasks: config/tn_uuid.yml
    - import_tasks: lsp/vif_id.yml
    - import_tasks: vif/int_br_name.yml
    - import_tasks: validation/vif_id_check.yml
    - import_tasks: validation/static_input_check.yml
    - import_tasks: config/app_intf_name.yml
    - import_tasks: lsp/create_lsp.yml
    - import_tasks: config/bms_config.yml
    - import_tasks: config/config.yml
    - import_tasks: vif/create_vif.yml
    - name: create bm dir
      file:
        path: /opt/vmware/nsx-bm
        state: directory
        mode: 0755
    - name: create manual restore script
      copy:
        src: ./manual/static_dhcp_manual_restore.sh
        dest: /opt/vmware/nsx-bm/static_dhcp_manual_restore.sh
        owner: root
        group: root
        mode: 0755
    - name: set IP address
      command: ifconfig {{ app_intf_name }} {{ static_ip }} netmask {{ netmask }}
    - import_tasks: vif/attach_vif.yml
    - import_tasks: route/route.yml
      when: routing_table is defined
    - import_tasks: config/config.yml
    - name: create bootup script
      template:
        src: templates/bms_static_init.j2
        dest: /etc/init.d/nsx-baremetal
        owner: root
        group: root
        mode: 0755
    - import_tasks: system/add_service_bootup.yml
