################################################################################
### Copyright (C) 2018 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
################################################################################
---
- hosts: TransportNodes
  tasks:
    - name: is ubuntu
      stat:
        path: /etc/lsb-release
      register: ubuntu_stat_result
    - name: is rhel
      stat:
        path: /etc/redhat-release
      register: rhel_stat_result
    - name: is suse
      stat:
        path: /etc/SuSE-release
      register: suse_stat_result
    - name: get miss dependency list
      command: cat /opt/baremetal/miss-dependency
      register: miss_dependency
    - debug:
        msg: "{{miss_dependency.stdout}}"
    - name: uninstall miss dependency
      package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ miss_dependency.stdout_lines }}"
      when: (ubuntu_stat_result.stat.exists == True) or (rhel_stat_result.stat.exists == True)
    - name: uninstall suse miss dependency
      zypper:
        name: "{{ item }}"
        state: absent
      with_items: "{{ miss_dependency.stdout_lines }}"
      when: suse_stat_result.stat.exists == True
