################################################################################
### Copyright (C) 2019 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause
################################################################################
---
- hosts: servers_static
  any_errors_fatal: true
  become_method: runas
  vars:
    ansible_become_password: "{{ ansible_password }}"
  tasks:
    - name: config mode
      set_fact:
        config_mode: 'static'
    - name: set os type
      delegate_to: localhost
      command: echo "Windows"
      register: os_type
    - import_tasks: windows/get_install_dir.yml
    - import_tasks: validation/static_input_check.yml
    - import_tasks: config/win_tn_uuid.yml
    - import_tasks: lsp/vif_id.yml
    - import_tasks: validation/vif_id_check.yml
    - import_tasks: config/app_intf_name.yml
    - import_tasks: lsp/create_lsp.yml
    - import_tasks: lsp/win_save_lsp_id.yml
    - import_tasks: vif/win_attach_vif.yml
