################################################################################
### Copyright (C) 2019 VMware, Inc.  All rights reserved.
### SPDX-License-Identifier: BSD-2-Clause
################################################################################
---
- hosts: servers_restoration
  any_errors_fatal: true
  become_method: runas
  vars:
    ansible_become_password: "{{ ansible_password }}"
  tasks:
    - import_tasks: windows/get_install_dir.yml
    - import_tasks: vif/win_detach_vif.yml
    - import_tasks: lsp/win_get_lsp_id.yml
    - import_tasks: lsp/delete_lsp.yml
